# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteaccesslogentry',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quoteaccesslogentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuoteAccessLogEntry',
        ),
    ]
