# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171208_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('tag',),
            },
        ),
        migrations.CreateModel(
            name='QuoteTagging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_at', models.DateTimeField(blank=True, null=True)),
                ('untagged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Quote')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MediaTag')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('director', models.TextField()),
                ('title', models.TextField()),
                ('year', models.TextField()),
                ('url', models.TextField()),
                ('retrieval_date', models.TextField()),
                ('source_tag', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title', 'author', 'director', 'year', 'url'),
            },
        ),
        migrations.CreateModel(
            name='SourceExcerpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pages', models.TextField()),
                ('begin_time', models.TextField()),
                ('end_time', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Source')),
            ],
            options={
                'ordering': ('content', 'pages', 'begin_time', 'end_time'),
            },
        ),
        migrations.CreateModel(
            name='SourceExcerptTagging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_at', models.DateTimeField(blank=True, null=True)),
                ('untagged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excerpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SourceExcerpt')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MediaTag')),
            ],
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='sourceexcerpt',
            name='tags',
            field=models.ManyToManyField(through='core.SourceExcerptTagging', to='core.MediaTag'),
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SourceType'),
        ),
        migrations.AddField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Source'),
        ),
        migrations.AddField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(through='core.QuoteTagging', to='core.MediaTag'),
        ),
    ]
